### ISSUE TITLE
[DOCUMENTATION] Incorrect Address for Gelato Network Rinkeby contract

### ISSUE THREAD

**Issue by dinahjohnson** [gelatodigital/ops#27]
The Gelato Network Rinkeby address on the docs is incorrect:
![image](https://user-images.githubusercontent.com/86927059/142486282-e3e5bdf2-ccc8-4e5a-9e87-65ed734c803f.png)

It looks like the Ropsten address was accidentally listed for Rinkeby:
![image](https://user-images.githubusercontent.com/86927059/142486492-16326ca6-0a85-4d5c-91e9-dc420a1bcea1.png)

Confirmed 0xCc4CcD69D31F9FfDBD3BFfDe49c6aA886DaB98d9 is the Ropsten address:
![image](https://user-images.githubusercontent.com/86927059/142486627-f4981ae1-a7b8-442b-ba23-62b99e9a5ab7.png)

**Comment by brandonchuah** [comment]
Fixed. Thanks for reporting!
