### ISSUE TITLE
Using Proxy Contracts

### ISSUE THREAD

**Issue by acemasterjb** [gelatodigital/ops#28]
What if I use proxy contracts for the contract to Poke/Automate?

I have a proxy contract that does delegate calls to an implementation/logic contract, if I use the address of the proxy contract in the Gelato Ops page it will therefore give me the functions for that proxy (the proxy is verified on etherscan so it gets its abi from there).

Is there a way to use a proxy contract on Gelato Ops?

**Comment by brandonchuah** [comment]
Gelato Ops UI will now fetch the ABI of the implementation contract automatically if Etherscan recognizes the proxy standard. If not, you can paste your own ABI.
