### ISSUE TITLE
Installing gelatodigital/ops via npm or yarn?

### ISSUE THREAD

**Issue by Foon256** [gelatodigital/ops#98]
Hi everybody,

I am trying to write a resolver contract which can also a contract creator for several bots. I looked into your examples and noticed
that I need to inherit `OpsTaskCreator.sol`

So I tried to install your public gelatodigital/ops as node-modul via `yarn add https://github.com/gelatodigital/ops.git`
and I am getting this error:
```
error C:\Github\EasyPI-Contract\node_modules\gelato-ops: Command failed.
Exit code: 1
Command: yarn husky install
Arguments:
Directory: C:\Github\EasyPI-Contract\node_modules\gelato-ops
Output:
```

my yarn version is 1.22.19

when I try the same with `npm install https://github.com/gelatodigital/ops.git`
I get the error:
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gelato-ops@1.0.0 postinstall: `yarn husky install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gelato-ops@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

my npn version is:  6.14.15

Is there a lib for the npm registry? If not, should I just dl the contracts and includ them manually?
Thanks for your help!

**Comment by goums** [comment]
hey @Foon256 

Thanks for the feedback.

> Is there a lib for the npm registry? If not, should I just dl the contracts and includ them manually?
Indeed, this `ops` smart contract repo is not meant to be installed via yarn/npm.
It showcase multiple examples, but the idea is just that you can copy/paste those that are relevant for your use case.

**Comment by Foon256** [comment]
Okay,

thanks for the feedback!
